/**
 * Источник — «Алхимия Сумрачного Доминиона. Справочник игрока», редакция 31 июля 2026: домашняя
 * система стола, а не SRD. Справочник приводит у свойства только название и направление — потому
 * здесь нет ни урона, ни длительности.
 */

export const ALCHEMY_DIRECTIONS = ["potions", "poisons", "transmutation"] as const;

export type AlchemyDirection = (typeof ALCHEMY_DIRECTIONS)[number];

export const ALCHEMICAL_RARITIES = [
  "common",
  "uncommon",
  "rare",
  "veryRare",
  "legendary",
] as const;

export type AlchemicalRarity = (typeof ALCHEMICAL_RARITIES)[number];

const DIRECTION_BY_PROPERTY = {
  "Лечение здоровья": "potions",
  "Регенерация здоровья": "potions",
  "Полное восстановление здоровья": "potions",
  "Временное здоровье": "potions",
  "Стабилизация": "potions",
  "Остановка кровотечения": "potions",
  "Подавление боли": "potions",
  "Лечение травм": "potions",
  "Восстановление органов и конечностей": "potions",
  "Пробуждение": "potions",
  "Снятие усталости": "potions",
  "Ускоренное восстановление во время короткого отдыха": "potions",
  "Лечение болезней": "potions",
  "Сопротивление болезням": "potions",
  "Противоядие": "potions",
  "Лечение паралича": "potions",
  "Лечение окаменения": "potions",
  "Восстановление органов чувств": "potions",
  "Разрыв связи с проклятым предметом": "potions",
  "Омоложение": "potions",
  "Старение": "potions",
  "Ускорение роста растений": "potions",
  "Воскрешение": "potions",
  "Восстановление маны": "potions",
  "Полное восстановление маны": "potions",
  "Увеличение максимума здоровья": "potions",
  "Снижение магического истощения": "potions",
  "Укрепление магических каналов": "potions",
  "Укрепление концентрации": "potions",
  "Усиление магического аспекта": "potions",
  "Повышение природной брони": "potions",
  "Сопротивление категории урона": "potions",
  "Иммунитет к категории урона": "potions",
  "Сопротивление типу урона": "potions",
  "Иммунитет к состоянию": "potions",
  "Защита рассудка": "potions",
  "Храбрость": "potions",
  "Защита от неблагоприятной среды": "potions",
  "Защита тела от магии": "potions",
  "Усиление спасброска": "potions",
  "Усиление характеристики": "potions",
  "Усиление навыка": "potions",
  "Усиление ремесла": "potions",
  "Усиление меткости": "potions",
  "Расширение диапазона критического успеха": "potions",
  "Усиление грузоподъёмности": "potions",
  "Ускорение движения": "potions",
  "Повышение инициативы": "potions",
  "Дополнительное действие": "potions",
  "Дополнительная реакция": "potions",
  "Увеличение дальности прыжка": "potions",
  "Защита от урона при падении": "potions",
  "Игнорирование труднопроходимой местности": "potions",
  "Скорость лазания": "potions",
  "Скорость плавания": "potions",
  "Продлённая задержка дыхания": "potions",
  "Снижение потребности в пище и воде": "potions",
  "Снижение потребности во сне": "potions",
  "Увеличение существа": "potions",
  "Уменьшение существа": "potions",
  "Изменение внешности": "potions",
  "Подражание голосу": "potions",
  "Временные жабры": "potions",
  "Временное природное оружие": "potions",
  "Эластичное тело": "potions",
  "Изменение обмена веществ": "potions",
  "Ночное зрение": "potions",
  "Слепое зрение": "potions",
  "Обострение зрения": "potions",
  "Обострение слуха": "potions",
  "Обострение обоняния": "potions",
  "Обнаружение жизни": "potions",
  "Магическое зрение": "potions",
  "Свечение тела": "potions",
  "Невидимость тела": "potions",
  "Ясность ума": "potions",
  "Усиление памяти": "potions",
  "Защита памяти": "potions",
  "Умиротворение": "potions",
  "Эмпатия": "potions",
  "Разговор с животными": "potions",
  "Общение с душами умерших": "potions",
  "Пророческое видение": "potions",
  "Жидкая удача": "potions",
  "Ядовитый урон": "poisons",
  "Кислотный урон": "poisons",
  "Некротический урон": "poisons",
  "Кровотечение": "poisons",
  "Патологическое свёртывание крови": "poisons",
  "Повреждение внутренних органов": "poisons",
  "Подавление дыхания": "poisons",
  "Болезнь": "poisons",
  "Лихорадка": "poisons",
  "Некроз": "poisons",
  "Отмирание конечности": "poisons",
  "Окаменение": "poisons",
  "Извращение плоти": "poisons",
  "Отсроченное повреждение": "poisons",
  "Снижение максимального здоровья": "poisons",
  "Подавление лечения": "poisons",
  "Запрет регенерации здоровья": "poisons",
  "Урон мане": "poisons",
  "Высасывание здоровья или магии": "poisons",
  "Подавление ячейки заклинаний": "poisons",
  "Запрет восстановления ячеек заклинаний": "poisons",
  "Повышение расхода ячеек заклинаний": "poisons",
  "Магическое истощение": "poisons",
  "Повреждение магических каналов": "poisons",
  "Срыв концентрации": "poisons",
  "Запрет концентрации": "poisons",
  "Магическая немота": "poisons",
  "Паралич": "poisons",
  "Замедление": "poisons",
  "Усталость": "poisons",
  "Нарушение координации": "poisons",
  "Головокружение": "poisons",
  "Дрожь": "poisons",
  "Судороги": "poisons",
  "Обездвиживание": "poisons",
  "Принудительное падение": "poisons",
  "Подавление действий": "poisons",
  "Подавление реакции": "poisons",
  "Оглушение": "poisons",
  "Недееспособность": "poisons",
  "Усыпление": "poisons",
  "Потеря сознания": "poisons",
  "Ложная смерть": "poisons",
  "Физическая немота": "poisons",
  "Слепота": "poisons",
  "Глухота": "poisons",
  "Потеря обоняния": "poisons",
  "Искажение вкуса": "poisons",
  "Обострение боли": "poisons",
  "Светобоязнь": "poisons",
  "Шумобоязнь": "poisons",
  "Рвота": "poisons",
  "Диарея": "poisons",
  "Галлюцинации": "poisons",
  "Безумие": "poisons",
  "Паника": "poisons",
  "Ярость": "poisons",
  "Спутанность сознания": "poisons",
  "Стирание памяти": "poisons",
  "Блокировка воспоминаний": "poisons",
  "Повышенная внушаемость": "poisons",
  "Алхимическая привязанность": "poisons",
  "Принуждение к правдивости": "poisons",
  "Навязчивое поведение": "poisons",
  "Неспособность различать союзников и врагов": "poisons",
  "Кошмары": "poisons",
  "Апатия": "poisons",
  "Ослабление характеристики": "poisons",
  "Ослабление навыка": "poisons",
  "Снижение меткости": "poisons",
  "Снижение инициативы": "poisons",
  "Подавление критических успехов": "poisons",
  "Уязвимость к категории урона": "poisons",
  "Уязвимость к типу урона": "poisons",
  "Повреждение природной брони": "poisons",
  "Ослабление сопротивления ядам": "poisons",
  "Ослабление сопротивления болезням": "poisons",
  "Зависимость": "poisons",
  "Синдром отмены": "poisons",
  "Бесплодие": "poisons",
  "Нарушение сна": "poisons",
  "Замедление естественного восстановления": "poisons",
  "Повышенная восприимчивость к следующей дозе": "poisons",
  "Скрытое носительство болезни": "poisons",
  "Взрыв": "transmutation",
  "Осколочный выброс": "transmutation",
  "Стихийный выброс": "transmutation",
  "Стихийное оружейное масло": "transmutation",
  "Кислотное оружейное покрытие": "transmutation",
  "Ядовитое оружейное покрытие": "transmutation",
  "Масло пробития брони": "transmutation",
  "Алхимическая заточка": "transmutation",
  "Клейкая смесь": "transmutation",
  "Опутывающая пена": "transmutation",
  "Дымовая завеса": "transmutation",
  "Ослепляющая вспышка": "transmutation",
  "Отбрасывающая волна": "transmutation",
  "Скользкая поверхность": "transmutation",
  "Труднопроходимая поверхность": "transmutation",
  "Замораживание поверхности": "transmutation",
  "Поджигание поверхности": "transmutation",
  "Тушение огня": "transmutation",
  "Временная преграда": "transmutation",
  "Временный мост": "transmutation",
  "Коррозия снаряжения": "transmutation",
  "Разрушение материала": "transmutation",
  "Упрочнение материала": "transmutation",
  "Размягчение материала": "transmutation",
  "Повышение хрупкости материала": "transmutation",
  "Восстановление прочности предмета": "transmutation",
  "Трансмутация природного материала": "transmutation",
  "Трансмутация драгоценного металла": "transmutation",
  "Изменение агрегатного состояния вещества": "transmutation",
  "Уменьшение предмета": "transmutation",
  "Увеличение предмета": "transmutation",
  "Облегчение предмета": "transmutation",
  "Утяжеление предмета": "transmutation",
  "Водоотталкивание": "transmutation",
  "Защита от коррозии": "transmutation",
  "Сохранение органической материи": "transmutation",
  "Ускоренное разложение органической материи": "transmutation",
  "Защитное покрытие предмета": "transmutation",
  "Светоотражающее покрытие": "transmutation",
  "Маскирующее покрытие": "transmutation",
  "Проявляющий порошок": "transmutation",
  "Алхимическая смазка": "transmutation",
  "Алхимический растворитель": "transmutation",
  "Алхимическая печать": "transmutation",
  "Освящение жидкости": "transmutation",
  "Очистка воды": "transmutation",
  "Очистка пищи": "transmutation",
  "Нейтрализация кислоты": "transmutation",
  "Нейтрализация яда вне организма": "transmutation",
  "Очистка воздуха": "transmutation",
  "Подавление запаха": "transmutation",
  "Индикатор яда": "transmutation",
  "Индикатор крови": "transmutation",
  "Магический проявитель": "transmutation",
  "Подавление магии": "transmutation",
  "Создание временного голема": "transmutation",
  "Хаотическая мутация материи": "transmutation",
} as const satisfies Record<string, AlchemyDirection>;

export type AlchemicalPropertyName = keyof typeof DIRECTION_BY_PROPERTY;

export const ALCHEMICAL_PROPERTIES: readonly { nameRu: string; direction: AlchemyDirection }[] =
  Object.entries(DIRECTION_BY_PROPERTY).map(([nameRu, direction]) => ({ nameRu, direction }));

export function isAlchemicalPropertyName(value: string): value is AlchemicalPropertyName {
  return value in DIRECTION_BY_PROPERTY;
}

export function alchemyDirectionOf(name: AlchemicalPropertyName): AlchemyDirection {
  return DIRECTION_BY_PROPERTY[name];
}
